version: '3.8'

services:
  php:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    container_name: symfony_php
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - symfony_net
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: symfony_postgres
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - symfony_net
    ports:
    - "5432:5432" 

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    ports:
      - "8080:80"
    networks:
      - symfony_net
    depends_on:
      - php

networks:
  symfony_net:
    driver: bridge
